kind: pipeline
type: ssh
name: deploy-kpiblocks

server:
  host: 
    from_secret: SERVER_HOST
  user: 
    from_secret: SERVER_USER
  password: 
    from_secret: SERVER_PASSWORD

steps:
  - name: build-and-deploy
    commands:
    - cd react
    - npm ci
    - npm run build
    - rm -r /var/www/kpiblocks/*
    - cp -r dist/* /var/www/kpiblocks/
    - echo "Deployment completed successfully!"

trigger:
  branch:
  - master
  event:
  - pull_request
  - push