kind: pipeline
type: ssh
name: deploy-kpiblocks

server:
  host: 
    from_secret: SERVER_HOST
  user: 
    from_secret: SERVER_USER
  password: 
    from_secret: SERVER_PASSWORD

steps:
  - name: clone-repository
    commands:
      - echo "Cloning repository..."
      - cd /tmp
      - rm -rf KPIBlocksDiagramViewer || true
      - git clone --depth 1 https://github.com/magarich228/KPIBlocksDiagramViewer.git
      - cd KPIBlocksDiagramViewer

  - name: build
    commands:
      - cd /tmp/KPIBlocksDiagramViewer/app
      - npm ci
      - npm run build

  - name: deploy
    commands:
      - echo "Deploying to /var/www/kpiblocks..."
      - sudo mkdir -p /var/www/kpiblocks
      - sudo rm -rf /var/www/kpiblocks/*
      - sudo cp -r /tmp/KPIBlocksDiagramViewer/app/dist/* /var/www/kpiblocks/
      - echo "Deployment completed!"
      - sudo ls -la /var/www/kpiblocks/

trigger:
  branch:
    - master
  event:
    - push