kind: pipeline
type: ssh
name: deploy-kpiblocks

server:
  host: 
    from_secret: SERVER_HOST
  user: 
    from_secret: SERVER_USER
  password: 
    from_secret: SERVER_PASSWORD

steps:
  - name: debug-info
    commands:
      - echo "Starting deployment.."
      - pwd
      - ls -la

trigger:
  branch:
    - master
  event:
    - push