kind: pipeline
type: ssh
name: deploy-kpiblocks

server:
  host: SERVER_HOST
  user: SERVER_USER
  password: SERVER_PASSWORD

steps:
  - name: debug-info
    commands:
      - echo "Starting deployment"
      - pwd
      - ls -la

trigger:
  branch:
    - master
  event:
    - push