kind: pipeline
type: docker
name: deploy-kpiblocks

volumes:
  - name: kpiblocksvol
    host:
      path: /var/www/kpiblocks

steps:
  - name: build-and-deploy
    image: node:18-alpine
    volumes:
      - name: kpiblocksvol
        path: /deploy
    commands:
      - cd react
      - npm ci
      - npm run build
      - cp -r dist/* /deploy/
      - echo "Deployment completed successfully!"